apiVersion: apps/v1  
kind: Deployment     
metadata:
  name: banking-app
  namespace: microservices  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      nodeSelector:
        kubernetes.io/hostname: ip-10-0-1-253.eu-west-2.compute.internal


      containers:
      - name: open-banking-web
        image: jayasowmiya/open-banking-web:latest
        imagePullPolicy: Never
        command: ["npm", "start"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:    
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          readOnlyRootFilesystem: true
