apiVersion: v1
kind: Service
metadata:
  name: banking-service
  namespace: microservices
spec:
  selector:
    app: banking-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer