apiVersion: v1
kind: Service
metadata:
  name: banking-service
  namespace: microservices
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080
  type: LoadBalancer