apiVersion: v1
kind: Service
metadata:
  name: banking-service
  namespace: microservices
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32767  
  type: NodePort  