- name: Configure DevOps Environment
  hosts: all
  become: yes
  tasks:
    
    # 1️⃣ Install System Dependencies
    - name: Update system packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install required dependencies
      apt:
        name:
          - curl
          - unzip
          - git
          - python3-pip
        state: present

    # 2️⃣ Install Terraform for Infrastructure Automation
    - name: Download Terraform
      shell: wget -q -O terraform.zip https://releases.hashicorp.com/terraform/1.5.5/terraform_1.5.5_linux_amd64.zip

    - name: Extract Terraform
      shell: unzip terraform.zip && mv terraform /usr/local/bin/

    - name: Verify Terraform installation
      command: terraform version

    # 3️⃣ Install Ansible for Configuration Management
    - name: Install Ansible
      apt:
        name: ansible
        state: present

    - name: Verify Ansible installation
      command: ansible --version

    # 4️⃣ Install Docker
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add Jenkins user to Docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    # 5️⃣ Install Kubernetes CLI (`kubectl`)
    - name: Download Kubernetes CLI
      shell: curl -LO "https://dl.k8s.io/release/v1.27.0/bin/linux/amd64/kubectl"

    - name: Move `kubectl` to `/usr/local/bin`
      shell: mv kubectl /usr/local/bin/kubectl && chmod +x /usr/local/bin/kubectl

    - name: Verify Kubernetes CLI installation
      command: kubectl version --client

    # 6️⃣ Install Helm for Kubernetes Package Management
    - name: Install Helm
      shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    # 7️⃣ Install Jenkins for CI/CD
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

    # 8️⃣ Deploy Prometheus & Grafana for Monitoring
    - name: Add Helm repositories
      shell: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update

    - name: Install Prometheus for monitoring
      shell: helm install monitoring-prometheus prometheus-community/prometheus --namespace monitoring --create-namespace

    - name: Install Grafana for dashboards
      shell: helm install monitoring-grafana grafana/grafana --namespace monitoring

    # 9️⃣ Verify Installed Services
    - name: Check running Docker containers
      command: docker ps

    - name: Check Kubernetes nodes
      command: kubectl get nodes

    - name: Check Jenkins status
      command: systemctl status jenkins