- name: Install and Configure Docker
  hosts: all
  become: yes
  tasks:
    - name: Update package cache
      yum:
        name: "*"
        state: latest

    - name: Install dependencies
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker repository
      shell: amazon-linux-extras enable docker

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes